title: Andrea Salvati
description: I am a Ph.D. candidate in the Department of Economics at Rice University. My research interests are Economics of Education, Labor Economics, and Applied Microeconomics.
show_downloads: false
theme: jekyll-theme-minimal
